/**
 * Settings-manifest defaults (ARCH-05).
 *
 * The Settings page used to hand-copy ~214 engine defaults into
 * `$lib/settings/manifest.ts`. Those numbers are what the field shows when the
 * backend has no stored value AND what the "Default: N" caption reads, so a
 * stale copy is the page telling an operator that a gate is stricter (or
 * looser) than the engine actually runs — on the page reviewed before arming
 * real capital. Nine of them had in fact drifted.
 *
 * The defaults now come from the backend. `manifest.ts` overlays a checked-in
 * snapshot (`backendDefaults.generated.json`, regenerated by
 * `python -m forven.settings_manifest` and pinned fresh by
 * `tests/test_finish_manifest.py`) at module load, so the page is correct with
 * no network call — in SSR, in unit tests, and when the backend is down.
 *
 * This module is the LIVE half: a running instance can hand the page its own
 * defaults, which self-heals a snapshot that was committed stale.
 *
 * NOT wired into the section components on purpose. `entry.default` is read
 * synchronously while a section renders, so a refresh that lands after mount
 * would not repaint the captions it changed — it belongs at the settings route's
 * load boundary, before the sections mount, and that file is outside this
 * change. The snapshot already covers every environment; this is the self-heal.
 *
 * Not re-exported from `$lib/api` either (that barrel lists exports by hand);
 * import from `$lib/api/settings` directly.
 */

import { fetchApi } from './core';
import { applyBackendDefaults } from '$lib/settings/manifest';

export interface SettingsManifestDefaults {
	/** `backendPath` -> default value, same key and units as GET /api/settings. */
	defaults: Record<string, unknown>;
	count: number;
	/** Which backend default registries fed the map (diagnostic). */
	sources: string[];
}

export function getSettingsManifestDefaults(): Promise<SettingsManifestDefaults> {
	return fetchApi<SettingsManifestDefaults>('/api/settings/manifest-defaults');
}

/**
 * Fetch the live defaults and overlay them onto the manifest.
 *
 * Fail-soft on purpose: the checked-in snapshot has already populated every
 * default by the time this runs, so a backend that is down or older than this
 * endpoint must leave the page working rather than blank out every caption.
 * Returns the number of entries updated, or 0 when the refresh could not run.
 */
export async function refreshSettingsManifestDefaults(): Promise<number> {
	try {
		const payload = await getSettingsManifestDefaults();
		const map = payload?.defaults;
		if (!map || typeof map !== 'object') return 0;
		return applyBackendDefaults(map);
	} catch {
		return 0;
	}
}
