"""Backend-owned default values for the Settings-page manifest (ARCH-05).

WHY THIS EXISTS
---------------
``frontend/src/lib/settings/manifest.ts`` describes every knob on the Settings
page: label, unit, area, description — and, historically, a hand-copied
``default`` per knob. That default is BOTH the "Default: N" caption under the
field and the value the field renders when the backend has no stored value.
Copying ~214 engine numbers into a TypeScript file means they drift, and they
did: nine gate thresholds had gone stale (quick-screen min trades captioned 30
against an engine running 20) on the page an operator reviews *before arming
real capital*. A caption that disagrees with the engine is a live-money hazard,
not a cosmetic bug.

This module is the single backend-side answer to "what does knob X default to?",
keyed by the manifest's own ``backendPath``. It re-declares nothing: every value
is read out of the dict that the runtime itself consults.

TWO CONSUMERS
-------------
1. ``GET /api/settings/manifest-defaults`` (forven/routers/system.py) — a live
   instance can hand its real defaults to the page.
2. ``frontend/src/lib/settings/backendDefaults.generated.json`` — a checked-in
   snapshot regenerated by ``python -m forven.settings_manifest`` and pinned
   fresh by ``tests/test_finish_manifest.py``. The frontend overlays it onto the
   manifest at module load, so the page shows engine truth with no network call
   (and in SSR, unit tests, and a backend-down browser).

The map mirrors what ``api_core.get_settings`` would return on an instance with
an empty KV, so a ``backendPath`` that resolves here resolves there too — same
key, same units.
"""

from __future__ import annotations

import copy
import json
import re
from pathlib import Path
from typing import Any

_FRONTEND_SETTINGS_DIR = Path(__file__).resolve().parents[1] / "frontend" / "src" / "lib" / "settings"

# Where the checked-in frontend snapshot lives. Regenerate with
#   python -m forven.settings_manifest
GENERATED_DEFAULTS_PATH = _FRONTEND_SETTINGS_DIR / "backendDefaults.generated.json"
MANIFEST_PATH = _FRONTEND_SETTINGS_DIR / "manifest.ts"

# Bookkeeping keys that are stamped per-load (timestamps, actor). They are not
# knobs, and including them would make the generated snapshot non-deterministic.
_NON_KNOB_KEYS = frozenset({"updated_at", "created_at", "created_by", "audit_log"})

# Leaf names that could carry a credential. The dicts below hold DEFAULTS (blank
# strings and flags), so nothing sensitive is reachable today — this is a
# standing guard so a future default can never leak through an endpoint whose
# only gate is operator access.
_SECRET_LEAF_MARKERS = ("private_key", "secret", "token", "password", "webhook_url", "api_key")


def _is_secret_leaf(path: str) -> bool:
    leaf = path.rsplit(".", 1)[-1].lower()
    return any(marker in leaf for marker in _SECRET_LEAF_MARKERS)


def _flatten(node: dict, prefix: str = "") -> dict[str, Any]:
    """Flatten nested dicts to dotted paths. Lists/scalars are leaves.

    Matches how the Settings components read a value: ``backendPath.split('.')``
    walked against the settings object.
    """
    out: dict[str, Any] = {}
    for key, value in node.items():
        if key in _NON_KNOB_KEYS:
            continue
        path = f"{prefix}{key}"
        if isinstance(value, dict):
            out.update(_flatten(value, f"{path}."))
        else:
            out[path] = value
    return out


def default_settings_tree() -> dict[str, Any]:
    """The settings object a fresh instance would serve, defaults only.

    Assembled in the SAME order as ``api_core.get_settings`` so the two cannot
    disagree about which layer wins:
      1. the main settings blob (plus its nested research / data-engine trees),
      2. the flat pipeline-settings payload, minus the keys that route to the
         policy config and minus the keys that must not shadow the blob,
      3. the policy pipeline config in DISPLAY units (ratio rails converted to
         whole percent exactly where ``pipeline_thresholds_for_display`` does).
    """
    from forven.api_core import (
        _PIPELINE_OVERLAY_SHADOWED_KEYS,
        _PIPELINE_THRESHOLD_SETTING_KEYS,
    )
    from forven.policy import DEFAULT_PIPELINE_CONFIG, pipeline_thresholds_for_display
    from forven.settings_apply import (
        _DEFAULT_PIPELINE_SETTINGS,
        _DEFAULT_SETTINGS_PAYLOAD,
        _default_data_engine_settings_payload,
        _default_research_settings_payload,
    )

    tree: dict[str, Any] = copy.deepcopy(_DEFAULT_SETTINGS_PAYLOAD)
    # Nested trees owned by their own modules; _default_settings_payload() adds
    # them the same way (it also stamps updated_at, which is why it is not used
    # here — the generated snapshot has to be byte-stable).
    tree["research_settings"] = _default_research_settings_payload()
    tree["data_engine_settings"] = _default_data_engine_settings_payload()

    for key, value in _DEFAULT_PIPELINE_SETTINGS.items():
        if key in _PIPELINE_THRESHOLD_SETTING_KEYS or key in _PIPELINE_OVERLAY_SHADOWED_KEYS:
            continue
        tree[key] = copy.deepcopy(value)

    display_config = pipeline_thresholds_for_display(copy.deepcopy(DEFAULT_PIPELINE_CONFIG))
    for key, value in display_config.items():
        # Same shadow rule as the settings overlay: a pipeline key must never
        # take over a blob key of the same name with a different meaning.
        if key in _PIPELINE_OVERLAY_SHADOWED_KEYS:
            continue
        tree[key] = value

    return tree


def _consumer_default_registries() -> list[tuple[str, dict[str, Any]]]:
    """Default dicts that live with their CONSUMER, already keyed by setting name.

    These knobs are read straight off the settings blob by the module that
    enforces them, so their defaults never appear in ``_DEFAULT_SETTINGS_PAYLOAD``
    — but they are the live-money caps an operator reviews before arming, so the
    page must not be the only place their numbers are written down.

    Only registries whose KEYS are already the setting names are pulled in;
    nothing here re-types a key/value pair by hand. Knobs whose default lives as
    a bare module constant (basket_runtime.DEFAULT_N_LEGS, …) or inline at the
    read site are deliberately left out — mapping those would reintroduce
    exactly the hand-copied table this module exists to delete. The manifest's
    own literal stays their fallback.

    Each import is fail-soft because this runs behind an HTTP endpoint and these
    are heavy modules: a broken import must degrade the map, not 500 the Settings
    page. A silent drop is not a silent regression —
    tests/test_finish_manifest.py asserts every one of these keys resolves, and
    the generated snapshot would go stale the moment one stopped.
    """
    registries: list[tuple[str, dict[str, Any]]] = []
    try:
        from forven.exchange.risk import _PORTFOLIO_BUDGET_DEFAULTS

        registries.append(("live_portfolio_budget", dict(_PORTFOLIO_BUDGET_DEFAULTS)))
    except Exception:
        pass
    try:
        from forven.exchange.liquidity import _LIQUIDITY_DEFAULTS

        registries.append(("live_liquidity_guard", dict(_LIQUIDITY_DEFAULTS)))
    except Exception:
        pass
    try:
        from forven.live_graduation import DEFAULTS as _GRADUATION_DEFAULTS

        registries.append(("live_graduation", dict(_GRADUATION_DEFAULTS)))
    except Exception:
        pass
    return registries


def manifest_default_values() -> dict[str, Any]:
    """``backendPath`` -> default value, for every path the backend can answer.

    A path missing from this map is not an error: the manifest keeps its own
    literal as the fallback (see ``_consumer_default_registries``). What the map
    promises is that a path present here carries the value the engine will
    actually use, in the units the field renders.
    """
    values = _flatten(default_settings_tree())
    for _source, registry in _consumer_default_registries():
        for key, value in registry.items():
            # The settings tree wins: a knob declared in BOTH places is served
            # from the blob, so that is the number the page will show.
            values.setdefault(key, value)
    return {path: value for path, value in sorted(values.items()) if not _is_secret_leaf(path)}


def manifest_defaults_payload() -> dict[str, Any]:
    """Response body for ``GET /api/settings/manifest-defaults``."""
    defaults = manifest_default_values()
    return {
        "defaults": defaults,
        "count": len(defaults),
        "sources": [
            "settings_payload",
            "pipeline_settings",
            "pipeline_policy_display",
            *[name for name, _ in _consumer_default_registries()],
        ],
    }


# --------------------------------------------------------------------------- #
# Generator side only — everything below reads manifest.ts. The ENDPOINT never
# does: the backend must be able to answer "what is the default for path X"
# without knowing a frontend file exists.
# --------------------------------------------------------------------------- #

# The manifest is a flat array of object literals with one field per line, so a
# regex reader is enough and keeps this runnable from the Python suite (no JS
# runtime). Mirrors the reader in tests/test_arch_wiring.py.
_MANIFEST_ENTRY_RE = r"\n  \{\n(.*?)\n  \},"
_MANIFEST_BACKEND_PATH_RE = r"^    backendPath: '([^']+)',?$"


def manifest_backend_paths(manifest_path: Path | None = None) -> list[str]:
    """Every ``backendPath`` declared in manifest.ts, sorted and de-duplicated."""
    target = Path(manifest_path) if manifest_path is not None else MANIFEST_PATH
    text = target.read_text(encoding="utf-8")
    paths: set[str] = set()
    for match in re.finditer(_MANIFEST_ENTRY_RE, text, re.S):
        found = re.search(_MANIFEST_BACKEND_PATH_RE, match.group(1), re.M)
        if found:
            paths.add(found.group(1))
    return sorted(paths)


def generated_defaults(manifest_path: Path | None = None) -> dict[str, Any]:
    """The subset of ``manifest_default_values()`` the manifest actually asks for.

    Pruned deliberately. Serving the whole 400-key map would make the checked-in
    snapshot go stale (and CI go red) every time an unrelated default moves —
    adding one model id to _DEFAULT_AGENT_MODEL_KEYS, say, which no Settings
    field renders. Restricting it to declared backendPaths means the file
    changes exactly when a knob the operator can see changes.
    """
    values = manifest_default_values()
    return {path: values[path] for path in manifest_backend_paths(manifest_path) if path in values}


def generated_defaults_json(manifest_path: Path | None = None) -> str:
    """The exact text of the checked-in frontend snapshot.

    Deterministic by construction (sorted keys, no timestamps) so the freshness
    test in tests/test_finish_manifest.py is a plain string compare.
    """
    header = (
        "GENERATED by `python -m forven.settings_manifest` from the backend's own "
        "default dicts (policy.DEFAULT_PIPELINE_CONFIG, settings_apply."
        "_DEFAULT_SETTINGS_PAYLOAD, and the consumer-side live-risk registries). "
        "Do not edit by hand — change the backend default and regenerate. "
        "tests/test_finish_manifest.py fails when this file is stale."
    )
    body = {"__generated__": header, "defaults": generated_defaults(manifest_path)}
    return json.dumps(body, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def write_generated_defaults(path: Path | None = None) -> bool:
    """Rewrite the checked-in snapshot. Returns True when the file changed."""
    target = Path(path) if path is not None else GENERATED_DEFAULTS_PATH
    text = generated_defaults_json()
    if target.exists() and target.read_text(encoding="utf-8") == text:
        return False
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(text, encoding="utf-8")
    return True


def main() -> int:
    changed = write_generated_defaults()
    print(f"{'wrote' if changed else 'up to date'}: {GENERATED_DEFAULTS_PATH}")
    return 0


if __name__ == "__main__":  # pragma: no cover - operator entry point
    raise SystemExit(main())
