import { describe, it, expect } from 'vitest';
import {
  SETTINGS_MANIFEST,
  SETTINGS_AREAS,
  SETTINGS_SUBSECTIONS,
  BACKEND_DEFAULTS,
  BACKEND_DEFAULTS_APPLIED,
  applyBackendDefaults,
  type SettingsEntry,
} from '$lib/settings/manifest';

describe('settings manifest invariants', () => {
  it('every entry has a description', () => {
    for (const e of SETTINGS_MANIFEST) {
      expect(e.description.trim().length, `missing description on ${e.id}`).toBeGreaterThan(0);
    }
  });

  it('every entry has a non-undefined default', () => {
    for (const e of SETTINGS_MANIFEST) {
      expect(e.default, `missing default on ${e.id}`).not.toBeUndefined();
    }
  });

  it('every entry lists a valid area', () => {
    const areas = new Set(SETTINGS_AREAS.map((a) => a.id));
    for (const e of SETTINGS_MANIFEST) {
      expect(areas.has(e.area), `${e.id} -> area ${e.area}`).toBe(true);
    }
  });

  it('every entry lists an existing subsection in its area', () => {
    const pairs = new Set(SETTINGS_SUBSECTIONS.map((s) => `${s.area}/${s.id}`));
    for (const e of SETTINGS_MANIFEST) {
      expect(pairs.has(`${e.area}/${e.subsection}`), `${e.id}`).toBe(true);
    }
  });

  it('every entry has a non-empty usedBy', () => {
    for (const e of SETTINGS_MANIFEST) {
      expect(e.usedBy.length, `${e.id}`).toBeGreaterThan(0);
    }
  });

  it('ids are unique', () => {
    const seen = new Set<string>();
    for (const e of SETTINGS_MANIFEST) {
      expect(seen.has(e.id), `duplicate ${e.id}`).toBe(false);
      seen.add(e.id);
    }
  });

  it('SETTINGS_AREAS has Home first and Danger Zone last', () => {
    expect(SETTINGS_AREAS[0].id).toBe('home');
    expect(SETTINGS_AREAS[SETTINGS_AREAS.length - 1].id).toBe('danger');
  });

  it('Danger Zone is flagged danger: true', () => {
    const danger = SETTINGS_AREAS.find((a) => a.id === 'danger');
    expect(danger?.danger).toBe(true);
  });
});

// ARCH-05: these suites used to pin each default to a number typed out here as
// well as in manifest.ts as well as in the engine — three copies of one value,
// and the copies drifted. `quick_screen.min_profit_factor` was pinned at 1.05
// while the engine's Default preset had relaxed to 1.0, so this file was
// actively holding a stale caption in place on the page an operator reviews
// before arming live capital. They now assert AGREEMENT with the backend map
// (backendDefaults.generated.json, regenerated by
// `python -m forven.settings_manifest`); what is pinned is that the knob exists,
// is wired to the right path, and carries the engine's own number.
function assertPipelineKnob(id: string, backendPath: string): SettingsEntry {
  const entry = SETTINGS_MANIFEST.find((e) => e.id === id);
  expect(entry, `${id} missing from manifest`).toBeDefined();
  expect(entry?.backendSection).toBe('pipeline');
  expect(entry?.backendPath).toBe(backendPath);
  expect(entry?.type).toBe('number');
  expect(entry?.area).toBe('lab');
  expect(
    Object.prototype.hasOwnProperty.call(BACKEND_DEFAULTS, backendPath),
    `${backendPath} is absent from the backend defaults map — the knob is wired ` +
      'to a path the engine does not serve, or the snapshot is stale',
  ).toBe(true);
  // Assert the COMMITTED SOURCE LITERAL, not `entry.default`. applyBackendDefaults
  // runs at module load and sets `entry.default = BACKEND_DEFAULTS[backendPath]`,
  // so asserting `entry.default` here would be true by construction and could
  // never fail on drift. `offlineDefault` holds the literal from manifest.ts —
  // the value the page actually shows when the snapshot is missing — so this
  // fails if someone edits the literal to something the engine does not use.
  const literal = Object.prototype.hasOwnProperty.call(entry as object, 'offlineDefault')
    ? (entry as SettingsEntry).offlineDefault
    : entry?.default;
  expect(literal, `${id} source literal disagrees with the backend`).toBe(
    BACKEND_DEFAULTS[backendPath],
  );
  return entry as SettingsEntry;
}

describe('M-15 gate-floor knobs are surfaced in the manifest', () => {
  // 2026-06-09 audit: these floors were hardcoded in forven/policy.py and the
  // wired settings were silently ignored. They must stay surfaced AND carry the
  // engine's own value — paper->live is the live-money gate.
  const expected: Array<{ id: string; backendPath: string }> = [
    { id: 'pipeline.quick_screen.min_profit_factor', backendPath: 'quick_screen.min_profit_factor' },
    { id: 'pipeline.gauntlet.min_oos_profit_factor', backendPath: 'gauntlet.min_oos_profit_factor' },
    { id: 'pipeline.paper_trading.min_profit_factor_live', backendPath: 'paper_trading.min_profit_factor_live' },
    {
      id: 'pipeline.paper_trading.pf_position_reduction_threshold',
      backendPath: 'paper_trading.pf_position_reduction_threshold',
    },
    { id: 'pipeline.paper_trading.max_oos_is_ratio', backendPath: 'paper_trading.max_oos_is_ratio' },
  ];

  for (const exp of expected) {
    it(`declares ${exp.id} with the backend's default`, () => {
      assertPipelineKnob(exp.id, exp.backendPath);
    });
  }

  it('quick_screen.min_profit_factor shows the relaxed Default-preset floor, not the old 1.05', () => {
    // The specific drift this suite used to enforce. The manifest LITERAL is
    // still 1.05 (tests/test_arch_wiring.py pins that divergence until both
    // ends can be changed together); what the page renders must be the engine's.
    const entry = assertPipelineKnob(
      'pipeline.quick_screen.min_profit_factor',
      'quick_screen.min_profit_factor',
    );
    expect(entry.default).toBe(1);
  });
});

describe('2026-06-13 launch-hardening knobs are surfaced in the manifest', () => {
  // These threshold knobs were added to the backend pipeline config; per the
  // no-dead-knobs / no-hardcoded-settings rule they must be editable from the
  // Settings page (not just the KV).
  const expected: Array<{ id: string; backendPath: string }> = [
    { id: 'pipeline.quick_screen.fitness_min_trades', backendPath: 'quick_screen.fitness_min_trades' },
    {
      id: 'pipeline.quick_screen.fitness_min_profit_factor',
      backendPath: 'quick_screen.fitness_min_profit_factor',
    },
    { id: 'pipeline.paper_trading.min_paper_sharpe', backendPath: 'paper_trading.min_paper_sharpe' },
    { id: 'pipeline.paper_trading.min_profit_factor_paper', backendPath: 'paper_trading.min_profit_factor_paper' },
  ];

  for (const exp of expected) {
    it(`declares ${exp.id} with the backend's default`, () => {
      assertPipelineKnob(exp.id, exp.backendPath);
    });
  }
});

describe('ARCH-05: manifest defaults come from the backend', () => {
  // The duplication itself is the defect. manifest.ts still carries a literal
  // per knob as the OFFLINE fallback, but the value the page uses is overlaid
  // from the backend at load. These tests fail if that overlay stops covering a
  // knob — i.e. if a hardcoded literal starts being what the operator sees.
  const overlaid = SETTINGS_MANIFEST.filter(
    (e) =>
      e.defaultFromBackend !== false &&
      e.backendPath &&
      Object.prototype.hasOwnProperty.call(BACKEND_DEFAULTS, e.backendPath),
  );

  it('the snapshot is populated and covers most of the manifest', () => {
    expect(Object.keys(BACKEND_DEFAULTS).length).toBeGreaterThan(150);
    expect(BACKEND_DEFAULTS_APPLIED).toBeGreaterThan(150);
    expect(overlaid.length).toBe(BACKEND_DEFAULTS_APPLIED);
  });

  it('no overlaid entry disagrees with the backend', () => {
    const drift: string[] = [];
    for (const entry of overlaid) {
      const backendValue = BACKEND_DEFAULTS[entry.backendPath];
      if (entry.default !== backendValue) {
        drift.push(`${entry.id} -> ${entry.backendPath}: ${entry.default} != ${backendValue}`);
      }
    }
    expect(drift, `manifest defaults disagree with the backend:\n  ${drift.join('\n  ')}`).toEqual(
      [],
    );
  });

  it('only the documented %-shaped unit mirrors opt out of the overlay', () => {
    // Each of these renders a fraction-shaped backend rail in whole percent.
    // Overlaying would caption 0.4 under a "%" label. The real fix is to list
    // them in policy._UI_PERCENT_THRESHOLD_PATHS; until then they stay opted out
    // and this test stops the exemption from spreading.
    const optedOut = SETTINGS_MANIFEST.filter((e) => e.defaultFromBackend === false).map((e) => e.id);
    expect(optedOut.sort()).toEqual([
      'pipeline.gauntlet.mc_max_dd_p95',
      'pipeline.robustness_thresholds.param_jitter_pass_rate_min',
      'pipeline.robustness_thresholds.wfa_fold_pass_rate_min',
    ]);
    for (const id of optedOut) {
      const entry = SETTINGS_MANIFEST.find((e) => e.id === id);
      expect(entry?.unit, `${id} opts out of the overlay but is not a %-shaped mirror`).toBe('%');
    }
  });

  it('applyBackendDefaults ignores unknown paths and undefined values', () => {
    const entry: SettingsEntry = {
      id: 'test.entry',
      label: 'Test',
      default: 7,
      type: 'number',
      area: 'system',
      subsection: 'system-telemetry',
      backendSection: 'pipeline',
      backendPath: 'not_a_real_path',
      description: 'test',
      usedBy: ['test'],
    };
    expect(applyBackendDefaults({ other: 1 }, [entry])).toBe(0);
    expect(entry.default).toBe(7);
    expect(applyBackendDefaults({ not_a_real_path: undefined }, [entry])).toBe(0);
    expect(entry.default).toBe(7);
    expect(applyBackendDefaults({ not_a_real_path: 9 }, [entry])).toBe(1);
    expect(entry.default).toBe(9);
  });
});
